steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
          ["build", "-t",
          "asia-southeast2-docker.pkg.dev/$PROJECT_ID/sehatin-api/lstm-api",
          "."]

  - name: "gcr.io/cloud-builders/docker"
    args:
          ["push",
          "asia-southeast2-docker.pkg.dev/$PROJECT_ID/sehatin-api/lstm-api"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "lstm-api",
        "--image",
        "asia-southeast2-docker.pkg.dev/$PROJECT_ID/sehatin-api/lstm-api",
        "--region",
        "asia-southeast2",
        "--platform",
        "managed",
        "--port",
        "8080",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY